packages:
  - "apps/*"
  - "packages/*"

# Dependencias autorizadas a ejecutar postinstall
allowBuilds:
  esbuild: true
  "@prisma/client": true
  "@prisma/engines": true
  prisma: true
  sharp: true
  unrs-resolver: true
